# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app-deployment
  labels:
    app: netflix-app
spec:
  # Thiết lập 3 bản sao (Pod) cho khả năng chịu lỗi và hiệu suất
  replicas: 3
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
      - name: netflix-container
        # ⚠️ CHÚ Ý: Đổi tên image thành ECR_REPO của bạn.
        # Image này sẽ được cập nhật bởi CodeBuild (kubectl set image)
        image: 266735826560.dkr.ecr.us-east-1.amazonaws.com/devsecops/netflix-app:latest
        ports:
        - containerPort: 80 # Thay thế bằng cổng ứng dụng của bạn
        
        # Cấu hình Health Check để Kubernetes biết khi nào Pod đã sẵn sàng
        livenessProbe:
          httpGet:
            path: / # ⚠️ Thay thế bằng endpoint kiểm tra sức khỏe thực tế của bạn
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 3
        
        # Thiết lập giới hạn tài nguyên là một thực hành tốt
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "200m"-
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-app-service
  labels:
    app: netflix-app
spec:
  # Loại LoadBalancer sẽ tự động tạo một AWS Load Balancer (NLB/ALB)
  # Endpoint DNS của LB này sẽ là Primary Endpoint cho Route 53 Failover.
  type: LoadBalancer 
  
  # Selector phải khớp với 'labels' trong Deployment (app: netflix-app)
  selector:
    app: netflix-app 
  ports:
    # Cổng mà AWS Load Balancer (LB) lắng nghe từ người dùng (Internet)
    - protocol: TCP
      port: 80 
      # Cổng mà Container (Pod) của bạn đang lắng nghe (đã định nghĩa là 8080 trong Deployment)
      targetPort: 80
